"""Render and validate the M7 AWS Lightsail pre-apply package without cloud writes."""

from __future__ import annotations

import argparse
import ipaddress
import json
import re
from pathlib import Path
from typing import Any

NAME_RE = re.compile(r"^[a-z][a-z0-9-]{2,62}$")
HOST_RE = re.compile(r"^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$")
REPO_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
APPROVAL_KEYS = {
    "account",
    "region",
    "hostname",
    "budget_alert_and_no_hard_ceiling",
    "teardown_retention",
}
EXPECTED_EDGE = {
    "webhook": {
        "max_request_body_bytes": 26_214_400,
        "max_in_flight": 8,
        "rate_average": 1,
        "rate_period": "1s",
        "rate_burst": 20,
    },
    "viewer": {
        "max_request_body_bytes": 1_048_576,
        "max_in_flight": 32,
        "rate_average": 2,
        "rate_period": "1s",
        "rate_burst": 20,
    },
}


class PlanError(ValueError):
    """Raised when a pre-apply input is unsafe or incomplete."""


def _mapping(value: Any, name: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise PlanError(f"{name} must be an object")
    return value


def _exact_keys(data: dict[str, Any], expected: set[str], name: str) -> None:
    if set(data) != expected:
        raise PlanError(
            f"{name} fields mismatch: expected {sorted(expected)}, observed {sorted(data)}"
        )


def _text(data: dict[str, Any], key: str, *, pattern: re.Pattern[str] | None = None) -> str:
    value = data.get(key)
    if not isinstance(value, str) or not value:
        raise PlanError(f"{key} must be a non-empty string")
    if pattern is not None and pattern.fullmatch(value) is None:
        raise PlanError(f"{key} has an invalid value")
    return value


def _number(data: dict[str, Any], key: str) -> float:
    value = data.get(key)
    if isinstance(value, bool) or not isinstance(value, (int, float)) or value < 0:
        raise PlanError(f"{key} must be a non-negative number")
    return float(value)


def _positive_int(data: dict[str, Any], key: str) -> int:
    value = data.get(key)
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise PlanError(f"{key} must be a positive integer")
    return value


def _absolute_path(root: str, *parts: str) -> str:
    return str(Path(root).joinpath(*parts))


def _validate_admin_cidrs(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        raise PlanError("admin_cidrs must contain at least one restricted network")
    result = []
    for row in value:
        try:
            network = ipaddress.ip_network(str(row), strict=False)
        except ValueError as exc:
            raise PlanError(f"invalid admin CIDR: {row}") from exc
        minimum_prefix = 24 if network.version == 4 else 64
        if network.prefixlen < minimum_prefix:
            raise PlanError(f"admin CIDR is too broad: {network}")
        result.append(str(network))
    return result


def _edge_limits(edge: dict[str, Any], lane: str) -> dict[str, Any]:
    values = _mapping(edge.get(lane), f"edge.{lane}")
    _exact_keys(values, set(EXPECTED_EDGE[lane]), f"edge.{lane}")
    result = {
        "max_request_body_bytes": _positive_int(values, "max_request_body_bytes"),
        "max_in_flight": _positive_int(values, "max_in_flight"),
        "rate_average": _positive_int(values, "rate_average"),
        "rate_period": _text(values, "rate_period"),
        "rate_burst": _positive_int(values, "rate_burst"),
    }
    if re.fullmatch(r"[1-9][0-9]*(?:ms|s|m|h)", result["rate_period"]) is None:
        raise PlanError(f"edge.{lane}.rate_period is invalid")
    if result != EXPECTED_EDGE[lane]:
        raise PlanError(f"edge.{lane} must match the reviewed public limit contract")
    return result


def _toml(hostname: str, edge: dict[str, dict[str, Any]]) -> str:
    webhook = edge["webhook"]
    viewer = edge["viewer"]
    return f'''# Generated by scripts/render_preapply_plan.py; do not edit.
[http.routers.http-redirect]
entryPoints = ["web"]
rule = "Host(`{hostname}`)"
middlewares = ["https-redirect"]
service = "viewer"

[http.routers.webhook]
entryPoints = ["websecure"]
rule = "Host(`{hostname}`) && Path(`/webhooks/github`)"
priority = 100
middlewares = ["webhook-rate", "webhook-inflight", "webhook-body", "security-headers"]
service = "receiver"

[http.routers.webhook.tls]
certResolver = "letsencrypt"

[http.routers.viewer]
entryPoints = ["websecure"]
rule = "Host(`{hostname}`)"
middlewares = ["viewer-rate", "viewer-inflight", "viewer-body", "security-headers", "compress"]
service = "viewer"

[http.routers.viewer.tls]
certResolver = "letsencrypt"

[http.middlewares.https-redirect.redirectScheme]
scheme = "https"
permanent = true

[http.middlewares.webhook-rate.rateLimit]
average = {webhook['rate_average']}
period = "{webhook['rate_period']}"
burst = {webhook['rate_burst']}

[http.middlewares.webhook-inflight.inFlightReq]
amount = {webhook['max_in_flight']}

[http.middlewares.webhook-body.buffering]
maxRequestBodyBytes = {webhook['max_request_body_bytes']}

[http.middlewares.viewer-rate.rateLimit]
average = {viewer['rate_average']}
period = "{viewer['rate_period']}"
burst = {viewer['rate_burst']}

[http.middlewares.viewer-inflight.inFlightReq]
amount = {viewer['max_in_flight']}

[http.middlewares.viewer-body.buffering]
maxRequestBodyBytes = {viewer['max_request_body_bytes']}

[http.middlewares.security-headers.headers]
stsSeconds = 31536000
frameDeny = true
contentTypeNosniff = true
referrerPolicy = "no-referrer"
permissionsPolicy = "camera=(), microphone=(), geolocation=()"

[http.middlewares.compress.compress]

[http.services.receiver.loadBalancer]
passHostHeader = true

[[http.services.receiver.loadBalancer.servers]]
url = "http://receiver:8000"

[http.services.viewer.loadBalancer]
passHostHeader = true

[[http.services.viewer.loadBalancer.servers]]
url = "http://viewer:8501"

[tls.options.default]
minVersion = "VersionTLS12"
sniStrict = true
'''


def render_plan(source: dict[str, Any]) -> tuple[dict[str, Any], str, str]:
    """Validate an input and return plan JSON, Traefik TOML and a value-free env file."""

    if source.get("schema_version") != 1:
        raise PlanError("schema_version must be 1")
    _exact_keys(
        source,
        {
            "schema_version",
            "example_only",
            "provider",
            "resources",
            "application",
            "network",
            "edge",
            "backup",
            "cost",
            "approvals",
        },
        "input",
    )
    example_only = source.get("example_only")
    if not isinstance(example_only, bool):
        raise PlanError("example_only must be boolean")

    provider = _mapping(source.get("provider"), "provider")
    _exact_keys(provider, {"name", "account_id", "region", "availability_zone"}, "provider")
    if provider.get("name") != "aws_lightsail":
        raise PlanError("provider.name must be aws_lightsail")
    account_id = _text(provider, "account_id")
    if re.fullmatch(r"[0-9]{12}", account_id) is None:
        raise PlanError("provider.account_id must be a 12-digit AWS account ID")
    region = _text(provider, "region")
    availability_zone = _text(provider, "availability_zone")
    if region != "ap-southeast-1" or not availability_zone.startswith(f"{region}"):
        raise PlanError("this reviewed plan is restricted to ap-southeast-1")

    resources = _mapping(source.get("resources"), "resources")
    _exact_keys(
        resources,
        {
            "instance_name",
            "bundle_id",
            "blueprint_id",
            "static_ip_name",
            "disk_name",
            "disk_size_gib",
        },
        "resources",
    )
    names = {
        key: _text(resources, key, pattern=NAME_RE)
        for key in ("instance_name", "static_ip_name", "disk_name")
    }
    bundle_id = _text(resources, "bundle_id")
    blueprint_id = _text(resources, "blueprint_id")
    if bundle_id != "small_3_0":
        raise PlanError("resources.bundle_id must be small_3_0")
    if blueprint_id != "ubuntu_24_04":
        raise PlanError("resources.blueprint_id must be ubuntu_24_04")
    disk_size_gib = _positive_int(resources, "disk_size_gib")
    if disk_size_gib != 20:
        raise PlanError("resources.disk_size_gib must be 20")

    application = _mapping(source.get("application"), "application")
    _exact_keys(
        application,
        {
            "github_repo",
            "app_image",
            "public_product_name",
            "public_ask",
            "openrouter_deployed",
            "durable_root",
            "secret_root",
        },
        "application",
    )
    github_repo = _text(application, "github_repo", pattern=REPO_RE)
    app_image = _text(application, "app_image")
    if re.fullmatch(r"[A-Za-z0-9._/-]+:[A-Za-z0-9._-]+", app_image) is None or app_image.endswith(
        ":latest"
    ):
        raise PlanError("application.app_image must use an explicit non-latest tag")
    if not example_only and re.fullmatch(r"[0-9a-f]{40}", app_image.rsplit(":", 1)[1]) is None:
        raise PlanError("a real application image tag must be the exact 40-character Git SHA")
    product_name = _text(application, "public_product_name")
    if application.get("public_ask") is not False:
        raise PlanError("public Ask must remain disabled")
    if application.get("openrouter_deployed") is not False:
        raise PlanError("OpenRouter credentials must not be deployed")
    durable_root = _text(application, "durable_root")
    secret_root = _text(application, "secret_root")
    if not Path(durable_root).is_absolute() or not Path(secret_root).is_absolute():
        raise PlanError("durable_root and secret_root must be absolute")
    if Path(durable_root) == Path(secret_root) or Path(durable_root) in Path(secret_root).parents:
        raise PlanError("secret_root must stay outside the durable data volume")
    if durable_root != "/srv/issue-graphrag" or secret_root != "/etc/issue-graphrag/secrets":
        raise PlanError("application paths must match the reviewed host mount contract")

    network = _mapping(source.get("network"), "network")
    _exact_keys(
        network,
        {"hostname", "acme_email", "admin_cidrs", "public_tcp_ports"},
        "network",
    )
    hostname = _text(network, "hostname", pattern=HOST_RE)
    acme_email = _text(network, "acme_email")
    if re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", acme_email) is None:
        raise PlanError("network.acme_email is invalid")
    admin_cidrs = _validate_admin_cidrs(network.get("admin_cidrs"))
    if network.get("public_tcp_ports") != [80, 443]:
        raise PlanError("only TCP 80/443 may be public")
    reserved_hosts = (".example.com", ".example.org", ".example.net", ".test", ".invalid", ".localhost")
    if not example_only and hostname.endswith(reserved_hosts):
        raise PlanError("a real plan requires a real public hostname")

    edge_source = _mapping(source.get("edge"), "edge")
    _exact_keys(edge_source, {"image", "webhook", "viewer"}, "edge")
    if edge_source.get("image") != "traefik:v3.6.14":
        raise PlanError("edge.image must pin traefik:v3.6.14")
    edge = {lane: _edge_limits(edge_source, lane) for lane in ("webhook", "viewer")}

    backup = _mapping(source.get("backup"), "backup")
    _exact_keys(
        backup,
        {
            "automatic_disk_snapshot",
            "snapshot_time_utc",
            "automatic_snapshot_retention_days",
            "final_manual_snapshot_retention_days",
        },
        "backup",
    )
    if backup.get("automatic_disk_snapshot") is not True:
        raise PlanError("automatic disk snapshots must remain enabled")
    snapshot_time = _text(backup, "snapshot_time_utc")
    if re.fullmatch(r"(?:[01][0-9]|2[0-3]):00", snapshot_time) is None:
        raise PlanError("snapshot_time_utc must use an hourly UTC boundary")
    if backup.get("automatic_snapshot_retention_days") != 7:
        raise PlanError("Lightsail automatic snapshot retention must be recorded as 7 days")
    final_retention = _positive_int(backup, "final_manual_snapshot_retention_days")
    if final_retention > 365:
        raise PlanError("final manual snapshot retention must not exceed 365 days")

    cost = _mapping(source.get("cost"), "cost")
    _exact_keys(
        cost,
        {
            "budget_name",
            "budget_alert_email",
            "instance_monthly_usd",
            "disk_monthly_usd",
            "expected_snapshot_monthly_usd",
            "seven_full_snapshots_monthly_usd",
            "egress_overage_usd_per_gib",
            "budget_alert_usd",
            "provider_hard_ceiling",
        },
        "cost",
    )
    budget_name = _text(cost, "budget_name", pattern=NAME_RE)
    budget_alert_email = _text(cost, "budget_alert_email")
    if re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", budget_alert_email) is None:
        raise PlanError("cost.budget_alert_email is invalid")
    instance_cost = _number(cost, "instance_monthly_usd")
    disk_cost = _number(cost, "disk_monthly_usd")
    expected_snapshot = _number(cost, "expected_snapshot_monthly_usd")
    seven_full_snapshots = _number(cost, "seven_full_snapshots_monthly_usd")
    egress_overage = _number(cost, "egress_overage_usd_per_gib")
    budget_alert = _number(cost, "budget_alert_usd")
    if cost.get("provider_hard_ceiling") is not False:
        raise PlanError("Lightsail/Budgets cannot be represented as a provider hard ceiling")
    if (instance_cost, disk_cost, expected_snapshot, seven_full_snapshots, egress_overage) != (
        12.0,
        2.0,
        1.0,
        7.0,
        0.12,
    ):
        raise PlanError("cost inputs must match the 2026-08-26 official-price review")
    expected_monthly = round(instance_cost + disk_cost + expected_snapshot, 2)
    storage_stress_monthly = round(instance_cost + disk_cost + seven_full_snapshots, 2)
    if budget_alert < expected_monthly:
        raise PlanError("budget alert must not be below expected monthly cost")

    approvals = _mapping(source.get("approvals"), "approvals")
    if set(approvals) != APPROVAL_KEYS or any(not isinstance(value, bool) for value in approvals.values()):
        raise PlanError(f"approvals must contain booleans for {sorted(APPROVAL_KEYS)}")
    blockers = [f"approval missing: {key}" for key in sorted(APPROVAL_KEYS) if not approvals[key]]
    if example_only:
        blockers.insert(0, "example input cannot authorize apply")

    secret_files = [
        {
            "compose_name": "github_token",
            "host_path": _absolute_path(secret_root, "github_token"),
            "consumers": ["worker", "sync"],
            "minimum_permissions": [
                "Metadata: read",
                "Issues: read",
                "Pull requests: read",
            ],
        },
        {
            "compose_name": "github_webhook_secret",
            "host_path": _absolute_path(secret_root, "github_webhook_secret"),
            "consumers": ["receiver"],
            "minimum_permissions": ["random HMAC secret; no GitHub API permission"],
        },
    ]

    disk_paths = {
        "repos": _absolute_path(durable_root, "repos"),
        "analytics": _absolute_path(durable_root, "analytics"),
        "backups": _absolute_path(durable_root, "backups"),
        "traefik_acme": _absolute_path(durable_root, "traefik"),
    }
    dynamic_host_path = "/etc/issue-graphrag/traefik/dynamic.toml"
    read_only_preflight = [
        ["aws", "sts", "get-caller-identity"],
        ["aws", "lightsail", "get-regions", "--include-availability-zones", "--region", region],
        ["aws", "lightsail", "get-bundles", "--region", region],
        ["aws", "lightsail", "get-blueprints", "--region", region],
    ]
    apply_after_approval = [
        [
            "aws",
            "lightsail",
            "create-instances",
            "--region",
            region,
            "--availability-zone",
            availability_zone,
            "--blueprint-id",
            blueprint_id,
            "--bundle-id",
            bundle_id,
            "--instance-names",
            names["instance_name"],
        ],
        [
            "aws",
            "lightsail",
            "allocate-static-ip",
            "--region",
            region,
            "--static-ip-name",
            names["static_ip_name"],
        ],
        [
            "aws",
            "lightsail",
            "attach-static-ip",
            "--region",
            region,
            "--static-ip-name",
            names["static_ip_name"],
            "--instance-name",
            names["instance_name"],
        ],
        [
            "aws",
            "lightsail",
            "create-disk",
            "--region",
            region,
            "--availability-zone",
            availability_zone,
            "--disk-name",
            names["disk_name"],
            "--size-in-gb",
            str(disk_size_gib),
            "--add-ons",
            f"addOnType=AutoSnapshot,autoSnapshotAddOnRequest={{snapshotTimeOfDay={snapshot_time}}}",
        ],
        [
            "aws",
            "lightsail",
            "attach-disk",
            "--region",
            region,
            "--disk-name",
            names["disk_name"],
            "--instance-name",
            names["instance_name"],
            "--disk-path",
            "/dev/xvdf",
        ],
        [
            "aws",
            "lightsail",
            "put-instance-public-ports",
            "--region",
            region,
            "--instance-name",
            names["instance_name"],
            "--port-infos",
            json.dumps(
                [
                    {"fromPort": 22, "toPort": 22, "protocol": "tcp", "cidrs": admin_cidrs},
                    {
                        "fromPort": 80,
                        "toPort": 80,
                        "protocol": "tcp",
                        "cidrs": ["0.0.0.0/0"],
                    },
                    {
                        "fromPort": 443,
                        "toPort": 443,
                        "protocol": "tcp",
                        "cidrs": ["0.0.0.0/0"],
                    },
                ],
                separators=(",", ":"),
            ),
        ],
        [
            "aws",
            "budgets",
            "create-budget",
            "--account-id",
            account_id,
            "--budget",
            json.dumps(
                {
                    "BudgetName": budget_name,
                    "BudgetLimit": {"Amount": str(budget_alert), "Unit": "USD"},
                    "BudgetType": "COST",
                    "TimeUnit": "MONTHLY",
                },
                separators=(",", ":"),
            ),
            "--notifications-with-subscribers",
            json.dumps(
                [
                    {
                        "Notification": {
                            "NotificationType": "ACTUAL",
                            "ComparisonOperator": "GREATER_THAN",
                            "Threshold": threshold,
                            "ThresholdType": "PERCENTAGE",
                        },
                        "Subscribers": [
                            {"SubscriptionType": "EMAIL", "Address": budget_alert_email}
                        ],
                    }
                    for threshold in (80, 100)
                ],
                separators=(",", ":"),
            ),
        ],
    ]

    plan = {
        "schema_version": 1,
        "approval_ready": not blockers,
        "approval_blockers": blockers,
        "cloud_mutations_executed": False,
        "provider": {
            "name": "AWS Lightsail",
            "account_id": account_id,
            "region": region,
            "availability_zone": availability_zone,
        },
        "resources": {
            **names,
            "bundle_id": bundle_id,
            "blueprint_id": blueprint_id,
            "disk_size_gib": disk_size_gib,
            "budget_name": budget_name,
        },
        "application": {
            "github_repo": github_repo,
            "app_image": app_image,
            "public_product_name": product_name,
            "public_url": f"https://{hostname}",
            "public_ask": False,
            "openrouter_deployed": False,
            "webhook_events": ["issues", "issue_comment", "pull_request", "issue_dependencies"],
        },
        "network": {
            "public_tcp_ports": [80, 443],
            "admin_tcp_port": 22,
            "admin_cidrs": admin_cidrs,
            "container_only_ports": [8000, 8501, 8082],
            "trusted_upstream_proxies": [],
            "tls": "Let's Encrypt HTTP-01 with automatic renewal",
        },
        "edge": {"image": "traefik:v3.6.14", **edge},
        "storage": {
            "durable_disk_paths": disk_paths,
            "secret_root_on_instance_disk": secret_root,
            "automatic_snapshot_time_utc": snapshot_time,
            "automatic_snapshot_retention_days": 7,
            "final_manual_snapshot_retention_days": final_retention,
        },
        "secrets": secret_files,
        "viewer_credential_boundary": "zero secret files and repository data mounted read-only",
        "cost": {
            "expected_monthly_usd": expected_monthly,
            "seven_full_snapshots_storage_stress_usd": storage_stress_monthly,
            "budget_alert_usd": budget_alert,
            "budget_alert_email": budget_alert_email,
            "provider_hard_ceiling": False,
            "egress_overage_usd_per_gib": egress_overage,
            "unbounded_cost_warning": "egress and snapshot churn mean an AWS budget is an alert, not a stop",
        },
        "read_only_preflight_commands": read_only_preflight,
        "apply_commands_after_review_and_user_approval": apply_after_approval,
        "rollback": [
            "stop public-proxy and application writers",
            "restore the last verified application backup or disk snapshot",
            "start receiver, worker, sync, viewer and public-proxy on the previous image digest",
            "verify liveness, readiness, status and a read-only GitHub sync",
        ],
        "teardown": [
            "stop all Compose services and create a verified final application backup",
            "copy the final automatic disk snapshot to a manual snapshot",
            "verify the manual snapshot before deleting the source disk",
            "delete instance, static IP and disk only after explicit confirmation",
            f"retain the final manual snapshot for {final_retention} days, then explicitly delete it",
        ],
    }

    env = "\n".join(
        [
            "# Generated paths and non-secret values; secret file contents are never rendered.",
            f"GITHUB_REPO={github_repo}",
            f"APP_IMAGE={app_image}",
            f"REPO_DATA_HOST={disk_paths['repos']}",
            f"RADAR_ANALYTICS_HOST={disk_paths['analytics']}",
            f"BACKUP_DATA_HOST={disk_paths['backups']}",
            f"GITHUB_TOKEN_FILE_HOST={_absolute_path(secret_root, 'github_token')}",
            f"GITHUB_WEBHOOK_SECRET_FILE_HOST={_absolute_path(secret_root, 'github_webhook_secret')}",
            f"TRAEFIK_DYNAMIC_CONFIG_HOST={dynamic_host_path}",
            f"TRAEFIK_ACME_DATA_HOST={disk_paths['traefik_acme']}",
            f"ACME_EMAIL={acme_email}",
            "",
        ]
    )
    return plan, _toml(hostname, edge), env


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    try:
        source = json.loads(args.input.read_text(encoding="utf-8"))
        plan, dynamic, env = render_plan(_mapping(source, "input"))
    except (OSError, json.JSONDecodeError, PlanError) as exc:
        raise SystemExit(f"pre-apply plan refused: {exc}") from None
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "preapply-plan.json").write_text(
        json.dumps(plan, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (args.output_dir / "traefik-dynamic.toml").write_text(dynamic, encoding="utf-8")
    (args.output_dir / "compose-public.env").write_text(env, encoding="utf-8")
    print(json.dumps({"approval_ready": plan["approval_ready"], "output_dir": str(args.output_dir)}))


if __name__ == "__main__":
    main()
